# Generated by Django 5.2.17 on 2026-09-21 18:17

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='title')),
                ('intro', models.TextField(blank=True, verbose_name='introduction')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('token', models.CharField(default=apps.core.models.new_token, editable=False, max_length=64, unique=True)),
                ('password_hash', models.CharField(blank=True, editable=False, max_length=128)),
                ('password_version', models.PositiveIntegerField(default=0, editable=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='available until')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('theme', models.CharField(choices=[('darkroom', 'Darkroom'), ('light-table', 'Light table'), ('photobook', 'Photo book'), ('contact-sheet', 'Contact sheet')], default='darkroom', max_length=20, verbose_name='theme')),
                ('downloads', models.CharField(choices=[('none', 'No downloads'), ('web', 'Web size'), ('original', 'Originals'), ('both', 'Web size and originals')], default='web', max_length=10, verbose_name='downloads')),
                ('allow_favorites', models.BooleanField(default=True, verbose_name='clients can mark favourites')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='clients can comment')),
                ('watermark', models.BooleanField(default=False, verbose_name='watermark web-size photos')),
                ('strip_gps', models.BooleanField(default=True, verbose_name='remove GPS location from photos')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galleries', to='clients.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'galleries',
                'ordering': ['-created_at'],
            },
        ),
    ]
