# Generated by Django 5.2.17 on 2026-09-21 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('galleries', '0001_initial'),
        ('photos', '0001_initial'),
        ('shoots', '0002_client_restrict'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='photos.photo', verbose_name='cover photo'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='shoot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galleries', to='shoots.shoot', verbose_name='shoot'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='studio',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio'),
        ),
        migrations.AddField(
            model_name='gallerysection',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='galleries.gallery'),
        ),
        migrations.AddField(
            model_name='gallerysection',
            name='studio',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio'),
        ),
    ]
