# Generated by Django 5.2.17 on 2026-09-21 18:34

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('galleries', '0002_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default=apps.core.models.new_token, editable=False, max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='galleries.gallery')),
                ('studio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio')),
            ],
            options={
                'verbose_name': 'visitor',
                'verbose_name_plural': 'visitors',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(choices=[('web', 'Web size'), ('original', 'Originals')], default='web', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('queued', 'Waiting'), ('building', 'Preparing'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('file', models.FileField(blank=True, max_length=255, upload_to='')),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_requests', to='galleries.gallery')),
                ('studio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='galleries.galleryvisitor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=2000, verbose_name='comment')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='galleries.gallery')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='photos.photo')),
                ('studio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='galleries.galleryvisitor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('view', 'Opened the gallery'), ('photo_view', 'Viewed a photo'), ('favorite', 'Marked a favourite'), ('comment', 'Commented'), ('download_photo', 'Downloaded a photo'), ('download_zip', 'Downloaded the gallery')], max_length=20)),
                ('ip_hash', models.CharField(blank=True, max_length=16)),
                ('device', models.CharField(blank=True, max_length=20)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='galleries.gallery')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.photo')),
                ('studio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='galleries.galleryvisitor')),
            ],
            options={
                'indexes': [models.Index(fields=['gallery', 'kind', 'created_at'], name='galleries_g_gallery_1400a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='photos.photo')),
                ('studio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='galleries.galleryvisitor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('visitor', 'photo'), name='one_favorite_per_photo')],
            },
        ),
    ]
