# Generated by Django 5.2.17 on 2026-09-21 17:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('maps_url', models.URLField(blank=True, verbose_name='map link')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('studio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('duration_minutes', models.PositiveIntegerField(default=120, verbose_name='duration (minutes)')),
                ('photo_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='photos included')),
                ('editing_days', models.PositiveSmallIntegerField(default=14, verbose_name='editing deadline (days after the shoot)')),
                ('delivery_days', models.PositiveSmallIntegerField(default=21, verbose_name='delivery deadline (days after the shoot)')),
                ('is_active', models.BooleanField(default=True, verbose_name='offered')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('studio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio')),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Shoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='title')),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('confirmed', 'Confirmed'), ('shot', 'Shot'), ('editing', 'Editing'), ('delivered', 'Delivered'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='inquiry', max_length=20, verbose_name='status')),
                ('status_changed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Taken from the package when left empty.', max_digits=10, verbose_name='price')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('inquiry_message', models.TextField(blank=True, editable=False, verbose_name='inquiry message')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shoots', to='clients.client', verbose_name='client')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoots', to='shoots.location', verbose_name='location')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoots', to='shoots.package', verbose_name='package')),
                ('studio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio')),
            ],
            options={
                'verbose_name': 'shoot',
                'verbose_name_plural': 'shoots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['studio', 'status'], name='shoots_shoo_studio__8b9b8d_idx')],
            },
        ),
    ]
