# Generated by Django 5.2.17 on 2026-09-21 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('shoots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoot',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shoots', to='clients.client', verbose_name='client'),
        ),
    ]
