# Generated by Django 5.2.17 on 2026-09-22 14:04

import apps.finance.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
        ('shoots', '0002_client_restrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('colour', models.CharField(max_length=7, verbose_name='colour')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('studio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio')),
            ],
            options={
                'verbose_name': 'expense category',
                'verbose_name_plural': 'expense categories',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='number')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year')),
                ('sequence', models.PositiveIntegerField(blank=True, null=True, verbose_name='sequence')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='issue date')),
                ('service_date', models.DateField(blank=True, null=True, verbose_name='service date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='VAT rate')),
                ('vat_note', models.CharField(blank=True, max_length=200, verbose_name='VAT note')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid')], default='draft', max_length=8, verbose_name='status')),
                ('pdf', models.FileField(blank=True, max_length=255, upload_to=apps.finance.models.invoice_pdf_path, verbose_name='PDF')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client', verbose_name='client')),
                ('shoot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='shoots.shoot', verbose_name='shoot')),
                ('studio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('method', models.CharField(choices=[('transfer', 'Bank transfer'), ('cash', 'Cash'), ('card', 'Card'), ('other', 'Other')], default='transfer', max_length=10, verbose_name='method')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='clients.client', verbose_name='client')),
                ('shoot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='shoots.shoot', verbose_name='shoot')),
                ('studio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.invoice', verbose_name='invoice')),
            ],
            options={
                'verbose_name': 'income',
                'verbose_name_plural': 'incomes',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=8, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit price')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.invoice', verbose_name='invoice')),
            ],
            options={
                'verbose_name': 'invoice line',
                'verbose_name_plural': 'invoice lines',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(verbose_name='year')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='last number')),
                ('studio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio')),
            ],
            options={
                'verbose_name': 'invoice sequence',
                'verbose_name_plural': 'invoice sequences',
            },
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('supplier', models.CharField(blank=True, max_length=120, verbose_name='supplier')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=8, verbose_name='interval')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.expensecategory', verbose_name='category')),
                ('studio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio')),
            ],
            options={
                'verbose_name': 'recurring expense',
                'verbose_name_plural': 'recurring expenses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VAT included')),
                ('supplier', models.CharField(blank=True, max_length=120, verbose_name='supplier')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('receipt', models.FileField(blank=True, max_length=255, upload_to=apps.finance.models.receipt_path, verbose_name='receipt')),
                ('period', models.DateField(blank=True, null=True, verbose_name='period')),
                ('studio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory', verbose_name='category')),
                ('recurring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.recurringexpense', verbose_name='recurring expense')),
            ],
            options={
                'verbose_name': 'expense',
                'verbose_name_plural': 'expenses',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('studio', 'name'), name='unique_category_name_per_studio'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('studio', 'number'), name='invoice_number_per_studio'),
        ),
        migrations.AddConstraint(
            model_name='invoicesequence',
            constraint=models.UniqueConstraint(fields=('studio', 'year'), name='unique_sequence_per_year'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('recurring__isnull', False)), fields=('recurring', 'period'), name='one_expense_per_period'),
        ),
    ]
