# Generated by Django 5.2.17 on 2026-09-21 15:20

import apps.core.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='studio name')),
                ('slug', models.SlugField(help_text='Your public portfolio lives at /p/<address>/.', max_length=60, unique=True, verbose_name='portfolio address')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='phone')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('vat_id', models.CharField(blank=True, max_length=32, verbose_name='tax number')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('vat_registered', models.BooleanField(default=False, verbose_name='VAT registered')),
                ('default_vat_rate', models.DecimalField(decimal_places=1, default=Decimal('22.0'), max_digits=4, verbose_name='default VAT rate (%)')),
                ('ics_token', models.CharField(default=apps.core.models.new_token, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'studio',
                'verbose_name_plural': 'studios',
            },
        ),
    ]
