# Generated by Django 5.2.17 on 2026-09-28 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='accent_colour',
            field=models.CharField(default='#c7955a', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')], verbose_name='gallery accent'),
        ),
        migrations.AddField(
            model_name='studio',
            name='logo',
            field=models.ImageField(blank=True, upload_to='branding/', verbose_name='studio logo'),
        ),
    ]
