# Generated by Django 5.2.17 on 2026-09-21 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('shoot', 'Shoot'), ('meeting', 'Client meeting'), ('editing_deadline', 'Editing deadline'), ('delivery_deadline', 'Delivery deadline'), ('personal', 'Personal')], default='shoot', max_length=24, verbose_name='type')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='title')),
                ('start', models.DateTimeField(verbose_name='starts')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='ends')),
                ('all_day', models.BooleanField(default=False, verbose_name='all day')),
                ('is_tentative', models.BooleanField(default=False, help_text='Not confirmed yet, e.g. an inquiry.', verbose_name='tentative')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='clients.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['start'],
            },
        ),
    ]
