# Generated by Django 5.2.17 on 2026-09-21 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('shoots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='shoots.location', verbose_name='location'),
        ),
        migrations.AddField(
            model_name='event',
            name='shoot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shoots.shoot', verbose_name='shoot'),
        ),
        migrations.AddField(
            model_name='event',
            name='studio',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['studio', 'start'], name='scheduling__studio__ed2a9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end__isnull', True), ('end__gte', models.F('start')), _connector='OR'), name='event_ends_after_start'),
        ),
    ]
