# Generated by Django 5.2.17 on 2026-09-21 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=80, verbose_name='last name')),
                ('partner_name', models.CharField(blank=True, help_text="For couples: the second person, shown next to the client's name.", max_length=120, verbose_name='partner')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='company')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='phone')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('vat_id', models.CharField(blank=True, max_length=32, verbose_name='tax number')),
                ('source', models.CharField(choices=[('portfolio', 'Portfolio inquiry'), ('referral', 'Referral'), ('instagram', 'Instagram'), ('other', 'Other')], default='other', max_length=20, verbose_name='came from')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('studio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['studio', 'email'], name='clients_cli_studio__406b0f_idx'), models.Index(fields=['studio', 'first_name', 'last_name'], name='clients_cli_studio__1c51af_idx')],
            },
        ),
    ]
