# Generated by Django 5.2.17 on 2026-09-21 18:17

import apps.photos.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original', models.FileField(max_length=255, upload_to=apps.photos.models.original_path)),
                ('original_name', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('exif', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Waiting'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('error', models.TextField(blank=True)),
                ('renditions', models.JSONField(blank=True, default=dict)),
                ('rendition_version', models.PositiveIntegerField(default=0)),
                ('lqip', models.TextField(blank=True)),
                ('dominant_color', models.CharField(blank=True, max_length=7)),
                ('luminance', models.FloatField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='galleries.gallery')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='galleries.gallerysection')),
                ('studio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField()),
                ('received_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Uploading'), ('complete', 'Complete'), ('failed', 'Failed')], default='open', max_length=10)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='galleries.gallery')),
                ('photo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.photo')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='galleries.gallerysection')),
                ('studio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio')),
            ],
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['gallery', 'position'], name='photos_phot_gallery_1524ee_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['status', 'created_at'], name='photos_uplo_status_3890cc_idx'),
        ),
    ]
