# Generated by Django 5.2.17 on 2026-09-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='blurhash',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
