# Generated by Django 5.2.17 on 2026-09-22 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
        ('galleries', '0003_galleryvisitor_downloadrequest_photocomment_and_more'),
        ('photos', '0001_initial'),
        ('shoots', '0002_client_restrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='phone')),
                ('desired_date', models.DateField(blank=True, null=True, verbose_name='preferred date')),
                ('message', models.TextField(max_length=4000, verbose_name='message')),
                ('ip_hash', models.CharField(blank=True, max_length=16)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clients.client')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoots.package', verbose_name='package')),
                ('shoot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='shoots.shoot')),
                ('studio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio')),
            ],
            options={
                'verbose_name': 'inquiry',
                'verbose_name_plural': 'inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('slug', models.SlugField(max_length=80, verbose_name='address')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('cover_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='photos.photo', verbose_name='cover photo')),
                ('studio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='title')),
                ('slug', models.SlugField(max_length=160, verbose_name='address')),
                ('intro', models.TextField(blank=True, verbose_name='story')),
                ('place', models.CharField(blank=True, max_length=120, verbose_name='place')),
                ('story_date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='show on the front page')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='portfolio.portfoliocategory', verbose_name='category')),
                ('cover_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='photos.photo', verbose_name='cover photo')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='galleries.gallery', verbose_name='photos from gallery')),
                ('studio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio')),
            ],
            options={
                'verbose_name': 'story',
                'verbose_name_plural': 'stories',
                'ordering': ['position', '-story_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioStoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='photos.photo')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='portfolio.portfoliostory')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='portfoliostory',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='stories', through='portfolio.PortfolioStoryPhoto', to='photos.photo'),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('headline', models.CharField(blank=True, help_text='One line under your name, e.g. “Wedding and portrait photography, Ljubljana”.', max_length=160, verbose_name='headline')),
                ('about', models.TextField(blank=True, verbose_name='about you')),
                ('look', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10, verbose_name='look')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('accept_inquiries', models.BooleanField(default=True, verbose_name='show the inquiry form')),
                ('seo_description', models.CharField(blank=True, help_text='Shown by search engines under your name. Up to 160 characters.', max_length=160, verbose_name='search description')),
                ('portrait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='photos.photo', verbose_name='portrait')),
                ('studio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.studio')),
            ],
            options={
                'verbose_name': 'portfolio',
                'constraints': [models.UniqueConstraint(fields=('studio',), name='one_portfolio_per_studio')],
            },
        ),
        migrations.AddConstraint(
            model_name='portfoliocategory',
            constraint=models.UniqueConstraint(fields=('studio', 'slug'), name='category_slug_per_studio'),
        ),
        migrations.AddConstraint(
            model_name='portfoliostoryphoto',
            constraint=models.UniqueConstraint(fields=('story', 'photo'), name='photo_once_per_story'),
        ),
        migrations.AddConstraint(
            model_name='portfoliostory',
            constraint=models.UniqueConstraint(fields=('studio', 'slug'), name='story_slug_per_studio'),
        ),
    ]
